name = "ei-api-gateway"
main = "src/index.ts"
compatibility_date = "2026-04-09"

[[d1_databases]]
binding = "DB"
database_name = "esquilo-invest-dev"
database_id = "e2a0b0a8-484d-4507-b21c-facf090481dd"
preview_database_id = "e2a0b0a8-484d-4507-b21c-facf090481dd"
migrations_dir = "../../infra/banco/migrations"

[env.production.d1_databases]
binding = "DB"
database_name = "esquilo-invest"
database_id = "e2a0b0a8-484d-4507-b21c-facf090481dd"
preview_database_id = "e2a0b0a8-484d-4507-b21c-facf090481dd"

[build.upload]
main = "src/index.ts"

[env.production.build.upload]
main = "src/index.ts"

[[triggers]]
crons = ["*/5 * * * *", "0 3 * * *"]
